### ISSUE TITLE
Broken file links in report from phpstan through duster

### ISSUE THREAD

**Issue by django23** [tighten/duster#127]
Hi,

When using `phpstan` or `composer analyze` in `duster.json` it seems the links to the files are changed. This makes it impossible click/open your favorite editor from the report in the terminal.

When running `composer analyze` directly, the links do work.

- duster.json
```json
{
    "scripts": {
        "lint": {
            "phpstan": ["composer", "analyze"]
        }
    },
    "processTimeout": 120
}
```

- phpstan.neon
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - app/

    # Level 9 is the highest level
    level: 5

    editorUrl: 'phpstorm://open?file=%%file%%&line=%%line%%'
```

Output of `composer analyze`
![CleanShot 2023-09-09 at 08 43 12](https://github.com/tighten/duster/assets/827397/d0d5c374-bd9c-43f6-b03e-4a3ffcf49539)

Output of `duster lint`
![CleanShot 2023-09-09 at 08 43 54](https://github.com/tighten/duster/assets/827397/db1a2c43-57e8-404f-80aa-fb1abbfa31da)
