### ISSUE TITLE
Github Actions cannot find PHPStan

### ISSUE THREAD

**Issue by jamesrweb** [tighten/duster#148]
When using the "out of the box" workflow to `fix` the project, the github action cannot seem to find `vendor/bin/phpstan`.

I tried to update the workflow myself to install the dependencies manually, etc, but it still doesn't work, any ideas?

## duster.json:

```json
{
    "scripts": {
        "lint": {
            "PHPStan": ["vendor/bin/phpstan", "analyse", "src", "tests", "-c", "phpstan.neon"]
        },
        "fix": {
            "PHPStan": ["vendor/bin/phpstan", "analyse", "src", "tests", "-c", "phpstan.neon"]
        }
    }
}
```

### Before:
```yaml
name: Duster Fix

# Commits made in here will not trigger any workflows
# Checkout Duster's documentation for a workaround

on:
    push:
        branches: [ master ]
    pull_request:

jobs:
  duster:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: "Duster Fix"
        uses: tighten/duster-action@v2
        with:
          args: fix

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Dusting
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
```

### After:

```yaml
name: Duster Fix

# Commits made in here will not trigger any workflows
# Checkout Duster's documentation for a workaround

on:
    push:
        branches: [ master ]
    pull_request:

jobs:
  duster:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.3

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --no-suggest --ignore-platform-reqs

      - name: Duster Fix
        uses: tighten/duster-action@v2
        with:
          args: fix

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Dusting
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
```

## Pipeline output:

Both workflows result in the same output, as is shown below.

![image](https://github.com/tighten/duster/assets/47126579/c0841c4b-da78-49d3-9de5-4832794f5626)

**Comment by driftingly** [comment]
Hi @jamesrweb, the Duster action uses a Dockerfile to install and run Duster. The action doesn't have access to the vendor folder.  I would just replace the call to the action with a call to Duster since you're installing your dependencies anyways. 

```
- name: Duster Fix
  run: vendor/bin/duster fix
```

**Comment by jamesrweb** [comment]
It just feels weird considering the recommendation to use the vendor path in the config and then you can't use it in the recommended CI workflow. It's a conflict, right?

**Comment by driftingly** [comment]
@jamesrweb I did some testing on my end your second action should work. 
Can you try removing `--no-dev` when doing the `composer install`

**Comment by jamesrweb** [comment]
I ended up with the following working configuration:

```yaml
name: Fix
 
on:
    push:
      branches: [ master ]
    pull_request:
 
jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: write
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug
 
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-suggest --ignore-platform-reqs

      - name: Duster fix
        uses: tighten/duster-action@v2
        with:
          args: fix
        
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply linting fixes
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
```
