### ISSUE TITLE
Figure out how to give GH Actions access to the Duster config files if they're not published

### ISSUE THREAD

**Issue by mattstauffer** [tighten/duster#18]

**Comment by mattstauffer** [comment]
If they're not published to the root, the GH Actions don't know to look for the published versions. How do we add that to the `lint.yml`? Maybe actually publish them in?

**Comment by mattstauffer** [comment]
Maybe we can use this?

https://github.com/marketplace/actions/copy-file

have it composer install (ouch) then copy the file in... 

like this?

```yml
      uses: canastro/copy-file-action@master
      with:
        source: "vendor/tightenco/duster/configs/.php_cs.dist"
        target: ".php_cs.dist"
        flags: "-n" # Don't overwrite file if it already exists
```

Feels super fragile though!
