### ISSUE TITLE
GitHub Action can't find Tighten sniff

### ISSUE THREAD

**Issue by vmitchell85** [tighten/duster#36]
I keep getting the following error for my PHPCS GitHub Action.

```
ERROR: Referenced sniff "Tighten" does not exist
```

I've only made minor changes to the files. (Update to PHP 8.0, adding composer auth.json, ignoring a few rules)

Here is my `liny.yml` and my `.phpcs.xml.dist` files:

<details>
  <summary><code>lint.yml</code></summary>

```yml
name: Lint

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    phpcs:
        name: PHPCS

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Add HTTP basic auth credentials
              run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

            - name: Install dependencies
              run: composer install --no-interaction --no-suggest --ignore-platform-reqs

            - name: PHPCS lint
              uses: chekalsky/phpcs-action@v1
              with:
                phpcs_bin_path: './vendor/bin/phpcs'

    tlint:
        name: TLint

        continue-on-error: false

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Add HTTP basic auth credentials
              run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

            - name: Install dependencies
              run: composer install --no-interaction --no-suggest --ignore-platform-reqs

            - name: Tlint Lint
              run: vendor/bin/tlint

```

</details>

<details>
  <summary><code>.phpcs.xml.dist</code></summary>

```xml
<?xml version="1.0"?>
<ruleset>
    <file>app</file>
    <file>config</file>
    <file>database</file>
    <file>public</file>
    <file>resources</file>
    <file>routes</file>
    <file>tests</file>

    <rule ref="Tighten"/>

    <rule ref="PSR1.Files.SideEffects">
        <exclude-pattern>public/index.php</exclude-pattern>
    </rule>
    <rule ref="PSR1.Methods.CamelCapsMethodName">
        <exclude-pattern>*</exclude-pattern>
    </rule>
    <rule ref="Squiz.Classes.ValidClassName">
        <exclude-pattern>REDACTED.php</exclude-pattern>
    </rule>

</ruleset>

```

</details>

No worries if you guys can't help. Been hacking on this for a while and can't seem to figure out the issue.

Thanks in advance!
